name: FurryCatasaurus
main: me.dinosphere.FurryCat.FurryCat
version: 1.1
description: >
             Core Plugin developed by Sam Taber
commands:
  spawn:
    description: Teleports a player to the set spawn.
  setspawn:
    description: Sets the world spawn.
  whois:
    description: Tells you stats about who a player is.